In [62]:
import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
pd.options.plotting.backend = 'plotly'

# from dsc80_utils import * # Feel free to uncomment and use this.

fp1 = '../data/league_2023.csv'

fp2 = '../data/league_2022.csv'

fp3 = '../data/league_2024.csv'

league23 = pd.read_csv(fp1)
league23[league23['patch'] == 13.09]

league22 = pd.read_csv(fp2)

league24 = pd.read_csv(fp3)

league22

list(league.columns)

# neeko = league[league['champion'] == 'Neeko']

# neeko = neeko[neeko['patch'] == 13.9]


neeko['patch'].value_counts()

# neeko


league22[league22['champion'] == 'neeko']
league22['champion'] == 'neeko'


#hi joyce


combined = pd.concat([league22, league23, league24])

neeko = combined[combined['champion'] == 'Neeko']
neeko

neeko[neeko['gameid'] == 'ESPORTSTMNT02_2557639']

/Users/elliekwang/miniforge3/envs/dsc80/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3508: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


gameid datacompleteness  url league  year split  \
16027  ESPORTSTMNT02_2557639         complete  NaN     EL  2022   NaN   

       playoffs                 date  game  patch  ...  opp_csat15  \
16027         0  2022-02-09 00:31:28     1  12.02  ...       126.0   

      golddiffat15 xpdiffat15 csdiffat15 killsat15 assistsat15 deathsat15  \
16027        381.0       97.0        3.0       1.0         3.0        0.0   

      opp_killsat15 opp_assistsat15 opp_deathsat15  
16027           2.0             0.0            1.0  

[1 rows x 131 columns]

In [63]:
len(combined['gameid'].unique())

25788

In [64]:
#hypothesis test: was playing neeko after the patch random or is 
#there a significant difference what happened before and after the patch





In [78]:
# combined = combined[combined['patch'] >= 12.11]
# combined.

In [79]:
league22['patch'].unique()
#11

array([12.01, 12.02, 12.03, 12.04, 12.05, 12.06, 12.07, 12.08, 12.09,
       12.1 , 12.11, 12.12, 12.13, 12.14, 12.15,   nan, 12.16, 12.17,
       12.18, 12.19, 12.2 , 12.21, 12.23])

In [80]:
league23['patch'].unique()

array([13.01, 13.03, 13.04, 13.05, 13.06,   nan, 13.07, 13.08, 13.09,
       13.1 , 13.11, 13.12, 13.13, 13.14, 13.15, 13.16, 13.17, 13.18,
       13.19, 13.2 , 13.21, 13.22, 13.24])

In [81]:
league24['patch'].unique()

array([13.24, 14.01, 14.02, 14.03,   nan, 14.04, 14.05])